// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QA_api.Context;

#nullable disable

namespace QA_api.Migrations
{
    [DbContext(typeof(Ctx))]
    [Migration("20230212183150_new")]
    partial class @new
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.11");

            modelBuilder.Entity("QA_api.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.HasKey("QuestionId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            Answer = "categorie1",
                            Category = "1.jpg",
                            Points = 15,
                            QuestionText = "ChaiseBoisMassif"
                        },
                        new
                        {
                            QuestionId = 2,
                            Answer = "categorsie1",
                            Category = "1.jpg",
                            Points = 15,
                            QuestionText = "ChaiseBoiscqsccsMassif"
                        },
                        new
                        {
                            QuestionId = 3,
                            Answer = "categossrie1",
                            Category = "1.jpg",
                            Points = 15,
                            QuestionText = "scqscsq"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
